#!/usr/bin/env bash

# This script is used to initiate a reimage of Apple Mac machines via BotDeploy. 
# It is required to be copied to the machines needing reimage as a first step in that process.
# Machines that have already been reimaged via BotDeploy will keep this file located in the /Volumes/BotDeploy Directory.
# If it does not already exist on the machine Copy via SSH, SCP, or KVM to the Desktop of an Admin User.
# This script installs necessary apps and modules required to connect to Azure, update KeyVault secrets for the Users created,
# and downloads the BotDeploy Launcher and configuration files to be used in the reimage.
# Step by Step instructions on its use can be found in the CNEKB document here: https://devdiv.visualstudio.com/Engineering/_wiki/wikis/CNEKB/24096/Process-Using-BotDeploy-to-image-MAC-machines

clear
ScriptVersion=3.0
RestoreStartTime=$(date "+%m/%d/%Y %H:%M:%S")

# Add in usage line

# Add in Dev URL parameter switch
LIST=0
ENV="prod"
## Parse command-line options.
## getopts spec ":u:w:c:d:t:le:":
##   leading ':' = silent mode (we handle errors ourselves; getopts won't print)
##   trailing ':' on a letter = that option requires an argument (read from \)
##   no trailing ':' (l) = boolean flag, no argument
## Flags: -u <NewUser> -w <WorkflowID> -c <CurrentPass> -d <Downgrade>
##        -t <Team> -l -e <dev|prod>
while getopts ":u:w:c:d:t:le:" arg; do
   case $arg in
	u) NewUser=$OPTARG;;
	w) WorkflowID=$OPTARG;;
	c) CurrentPass=$OPTARG;;
	d) Downgrade=$OPTARG;;
	t) Team=$OPTARG;;
	l) LIST=1;;
	e) ENV=$OPTARG;;
   esac
done

logfile=/Users/Shared/mac_image.log
printf "\n$(date) Start script to call BotDeploy process\n" | tee $logfile

## If required parameters were not passed, prompt user for input
if [ -z ${NewUser+x} ]; then read -p 'Enter username to use after OS installation: ' NewUser; fi
if [ -z ${Team+x} ]; then read -p 'Enter team name: ' Team; fi


## Sets variables
if [ "$ENV" = "dev" ]; then
	URL="https://bot-deploy-func-devdh2.azurewebsites.net/api"
elif [ "$ENV" = "prod" ]; then
	URL="https://bot-deploy-func-prod.azurewebsites.net/api"
else
	printf "\nError: Invalid environment '$ENV'. Use 'dev' or 'prod'.\n" | tee -a $logfile
	exit 1
fi
APIEndpoint="$URL/provision"

TokenName=BotDeployToken-$Team
MSVaultName=BotDeploy-$Team
MSVaultNameLocal=$MSVaultName-Local
TenantID="72f988bf-86f1-41af-91ab-2d7cd011db47"
MSSPAppID="8aefe1a2-afba-49d6-a15a-c9a0b34dfbe7"
PowerShellPath="/usr/local/bin/pwsh"
architecture=$(uname -m)
SQLDB="uip"
UIPSQLSrv='uipsqlsrv01.database.windows.net'
SQLVaultName="UIPSQL"
SQLUserName="uiplogger"

# Get latest PowerShell version from GitHub API tag_name
latest_version=$(curl -s https://api.github.com/repos/PowerShell/PowerShell/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')

if [[ $architecture = "arm64" ]]; then
	launcherFilename="launcher.arm64.zip"
	PowerShellDownload="https://github.com/PowerShell/PowerShell/releases/download/${latest_version}/powershell-${latest_version#v}-osx-arm64.pkg"
else
	launcherFilename="launcher.zip"
	PowerShellDownload="https://github.com/PowerShell/PowerShell/releases/download/${latest_version}/powershell-${latest_version#v}-osx-x64.pkg"
fi

AZAccountsnupkg="https://psg-prod-eastus.azureedge.net/packages/az.accounts.2.7.3.nupkg"
AZKeyVaultnupkg="https://psg-prod-eastus.azureedge.net/packages/az.keyvault.4.3.0.nupkg"


function_generate-password () {
	## Generate a random password for the DDFUNADM account
	printf "\n$(date) Creating random password for next use\n" | tee -a $logfile
	char=(0 1 2 3 4 5 6 7 8 9 a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z - _)
	max=${#char[*]}
	for ((i = 1; i <= 15 ; i++))do
	let rand=${RANDOM}%${max}
	password="${password}${char[$rand]}"
	done
	printf " Random password is $password\n" | tee -a $logfile
	printf "$(date) Done\n" | tee -a $logfile
}
function_get-SN-Hostname () {
	## Gets SN and Hostname from machine
	printf "\n$(date) Getting SN from machine\n" | tee -a $logfile
	CompSN=`ioreg -l | grep IOPlatformSerialNumber | awk '{ print $4 }' | tr -d '"'`
	printf "$(date) Done\n" | tee -a $logfile
	printf "\n$(date) Getting Hostname from machine\n" | tee -a $logfile
	MachineName=`scutil --get HostName`
	if [ $? -eq 0 ]
	then
		echo $MachineName
	else
		read -p 'Hostname not found in OS. Enter new HostName`: ' MachineName;
		scutil --set HostName $MachineName
	fi
	printf "$(date) Done\n" | tee -a $logfile
}
function_get-PowerShell () {
	## Install Rosetta to allow PowerShell install
	printf "\n$(date) Installing Rosetta to allow PowerShell install\n" | tee -a $logfile
	sudo softwareupdate --install-rosetta --agree-to-license
	printf "$(date) Done\n" | tee -a $logfile
	
	## Installs PowerShell
	printf "\n$(date) Downloading and installing Powershell - $PowerShellDownload\n" | tee -a $logfile
	curl -L -o  /tmp/powershell.pkg $PowerShellDownload
	## Following line may be needed for Big Sur 11.5 or higher
	##sudo xattr -rd com.apple.quarantine /tmp/powershell.pkg
	sudo installer -pkg /tmp/powershell.pkg -target /
	printf "$(date) Done\n" | tee -a $logfile
}

function_get-KV (){

	rm -rf /tmp/azaccounts/
	rm -rf /tmp/azkeyvault

	printf "\n$(date) Creating Powershell script to run to retrieve secret - $SecretName\n" | tee -a $logfile
	cat <<EOF > ./getsecret.ps1
if (Get-Command -Name Disable-AzContextAutosave -ErrorAction SilentlyContinue) {
	Disable-AzContextAutosave | Out-Null
} else {
	Write-Host "Disable-AzContextAutosave cmdlet not found. Ensure the Az.Accounts module is installed." -ForegroundColor Yellow
}
Set-Item Env:\\SuppressAzurePowerShellBreakingChangeWarnings "true"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
\$TenantID = "$TenantID"
\$SPAppID = "$SPAppID"
\$SPKey = "$Key"
\$VaultName = "$VaultName"
\$SecretName = "$SecretName"

# Install Modules
Install-Module -Name Az.Accounts -force -AllowClobber
Install-Module -Name Az.KeyVault -force -AllowClobber

# Connect to Azure
write-host " Connecting to Azure" -ForegroundColor green
Update-AzConfig -EnableLoginByWam \$false -LoginExperienceV2 Off -WarningAction Ignore -InformationAction Ignore | Out-Null
Connect-AzAccount -DeviceCode -Tenant \$TenantID -Subscription "UIP"
write-host "   Done" -ForegroundColor green

function Get-Token ([string]\$VaultName, [string]\$SecretName){
	# Get Key Vault Secret
	\$SecretTemp = Get-AzKeyVaultSecret -VaultName "\$VaultName" -Name "\$SecretName"
	\$SecureSecret = \$SecretTemp.SecretValue
	\$Secret = [System.Net.NetworkCredential]::new("", \$SecureSecret).Password
	if ([string]::IsNullOrEmpty(\$Secret)){\$Secret = \$SecretTemp.SecretValueText}
	\$Secret | Add-Content SecretFile1
	return \$Secret | Out-Null
}

function Get-Secret-NewUser ([string]\$VaultName, [string]\$SecretName){
	# Get Key Vault Secret
	\$SecretTemp = Get-AzKeyVaultSecret -VaultName "\$VaultName" -Name "\$SecretName"
	\$SecureSecret = \$SecretTemp.SecretValue
	\$Secret = [System.Net.NetworkCredential]::new("", \$SecureSecret).Password
	if ([string]::IsNullOrEmpty(\$Secret)){\$Secret = \$SecretTemp.SecretValueText}
	\$Secret | Add-Content SecretFile2
	return \$Secret | Out-Null
}

function Get-Secret-DDFun ([string]\$VaultName, [string]\$SecretName){
	# Get Key Vault Secret
	\$SecretTemp = Get-AzKeyVaultSecret -VaultName "\$VaultName" -Name "\$SecretName"
	\$SecureSecret = \$SecretTemp.SecretValue
	\$Secret = [System.Net.NetworkCredential]::new("", \$SecureSecret).Password
	if ([string]::IsNullOrEmpty(\$Secret)){\$Secret = \$SecretTemp.SecretValueText}
	\$Secret | Add-Content SecretFile3
	return \$Secret | Out-Null
}
function Invoke-DeleteSecret ([string]\$AdminVaultName, [string]\$MachineName){
	## Deletes exisiting key vault secret for machine
	if (-not (Get-AzKeyVaultSecret -VaultName \$AdminVaultName -Name "$MachineName" -ErrorAction SilentlyContinue)) {
	    Write-Host "No existing secret found for $MachineName in \$AdminVaultName"
	    return
	}

	if (Get-AzKeyVaultSecret -VaultName \$AdminVaultName -Name "$MachineName"){
    	Write-Host "  Deleting exisitng Key Vault Secret for local admin"
    	Remove-AzKeyVaultSecret -VaultName \$AdminVaultName -Name "$MachineName" -Force -Confirm:\$false -ErrorAction Ignore | Wait-Process
    	\$CheckCount1 = 0
    	while ((Get-AzKeyVaultSecret -VaultName \$AdminVaultName -Name "$MachineName" -InRemovedState) -eq \$null) {
    	    if (\$CheckCount1 -ge 120) {
    	        Write-Host "Timeout waiting for secret deletion" -ForegroundColor Red
    	        break
    	    }
    	    \$CheckCount1++
    	    Write-Progress -Activity "Waiting for secret deletion" -Status "Running Remove-AzKeyVaultSecret" -CurrentOperation "$CheckCount1"
    	    Start-Sleep -Seconds 1
    	}
    	Write-Progress "Complete" -Completed
	}
}

function Invoke-PurgeSecret ([string]\$AdminVaultName, [string]\$MachineName){
	Write-Host "  Purging exisitng Key Vault Secret after deletion"
    Remove-AzKeyVaultSecret -VaultName \$AdminVaultName -Name $MachineName -InRemovedState -Force -Confirm:\$false -ErrorAction Ignore | Wait-Process
	while (!((Get-AzKeyVaultSecret -VaultName \$AdminVaultName -Name $MachineName -InRemovedState) -eq \$null)){
       	\$CheckCount2++
       	Write-Progress -Activity "Waiting for secret purge" -Status "Running . . . " -CurrentOperation "$CheckCount2"
       	start-sleep 1
    }
    \$CheckCount2++
}

function Invoke-SetSecret ([string]\$AdminVaultName, [string]\$MachineName){
    Write-Host "  Setting Key Vault Secret"
	\$SecureLocalAdminPass = ConvertTo-SecureString -string $password -AsPlainText -Force
    while ((Get-AzKeyVaultSecret -VaultName \$AdminVaultName -Name $MachineName) -eq \$null){
        if (\$CheckCount3 -le '120'){
            \$CheckCount3++
            Write-Progress -Activity "Waiting for secret creation" -Status "Running Set-AzKeyVaultSecret -VaultName \$AdminVaultName -Name $MachineName -SecretValue xxxxxxxxxxxxxxxxxxxx" -CurrentOperation "$CheckCount3"
            start-sleep 1
            Set-AzKeyVaultSecret -VaultName \$AdminVaultName -Name $MachineName -SecretValue \$SecureLocalAdminPass -ErrorAction ignore | Out-Null
        } else {
        	Invoke-ErrorRestart "Error creating secret in Key Vault"
    	}
    }
}


Get-Token "$MSVaultName" "$TokenName"
Get-Secret-NewUser "$MSVaultName" "$NewUser"
Get-Secret-DDFun "$MSVaultName" "ddfun"
Invoke-DeleteSecret "$MSVaultNameLocal" "$MachineName"
Invoke-PurgeSecret "$MSVaultNameLocal" "$MachineName"
Invoke-SetSecret "$MSVaultNameLocal" "$MachineName"

\$Token | Add-Content SecretFile1
\$NewUserPass | Add-Content SecretFile2
\$ddfunPass | Add-Content SecretFile3

EOF

	printf "$(date) Done\n" | tee -a $logfile
	printf "\n$(date) Calling getsecret.ps1\n" | tee -a $logfile

	$PowerShellPath -file ./getsecret.ps1 #&>/dev/null

	export "Token=$(cat SecretFile1)" 
	export "NewUserPass=$(cat SecretFile2)" 
	export "ddfunPass=$(cat SecretFile3)"
		
	rm -f ./getsecret.ps1
	rm -f ./SecretFile1
	rm -f ./SecretFile2
	rm -f ./SecretFile3

	printf "$(date) Done\n" | tee -a $logfile
}


function_set-workflow (){
	## If workflow is passed, set the computer to use the new ID
	if [ -z ${WorkflowID+x} ]; then
		printf "\nNo WorkflowID passed . . . Using existing value\n" | tee -a $logfile
		## Read current workflow set for machine in DB
		CurrentWorkflowID=`curl -H "Authorization: ${Token[@]}" --request GET $URL/bot?serial=$CompSN`
		WorkflowID=`echo $CurrentWorkflowID | grep -o '"WorkflowID": *[^,]*' | grep -o '[^:]*$'`
	else
		printf "\n$(date) WorkflowID parameter passed . . . Setting to $WorkflowID\n" | tee -a $logfile
		curl -H "Authorization: ${Token[@]}" --request PUT --data '{"Hostname":"'$MachineName'","Serial":"'$CompSN'","WorkflowID":"'$WorkflowID'","Provision":true}' $URL/bot
		printf "$(date) Done\n" | tee -a $logfile
	fi
}
function_get-launcher (){
	## Gets launcher based on architecture
	echo "Architecture: ${architecture}"
	echo "Launcher filename: ${launcherFilename}"

	## Checks for previous version of launcher and deletes if exists
	rm -f $launcherFilename
	rm -rf launcher

	## Downloads the launcher zip file and extracts
	printf "\n$(date) Downloading the launcher zip file\n" | tee -a $logfile
		curl -sIH "Authorization: ${Token}" $URL/launcher?${architecture} | perl -n -e '/^Location: (.*)$/ && print "$1"' | tr -d '\r' | xargs curl -o $launcherFilename
if [ $? -ne 0 ]; then
	    printf "\n$(date) Error: Failed to download launcher\n" | tee -a $logfile
	    exit 1
	fi
	printf "$(date) Done\n\n$(date) Unzipping $launcherFilename\n" | tee -a $logfile
	unzip  $launcherFilename #&>/dev/null
	printf "$(date) Done\n" | tee -a $logfile
	cd launcher

	## Copy files from current OS to launcher folder
	cp -v -f /usr/bin/pkgbuild ./externalbin/pkgbuild
	cp -v -f /usr/bin/productbuild ./externalbin/productbuild
}
function_set-config () {
	## Creates config file that the launcher will use
	printf "\n$(date) Creating the config file\n" | tee -a $logfile
	rm -rf config.json
	touch config.json
	echo "{">> config.json
	echo  '"APIToken": "'$Token'",'>> config.json
	echo  '"APIEndpoint": "'$APIEndpoint'",'>> config.json
	echo "}">> config.json
	printf "$(date) Done\n" | tee -a $logfile
}
function_exec-launcher () {
	## Launches the launcher with the user/pass info. This is what starts the imaging process. 
	printf "\n$(date) Starting the launcher\n" | tee -a $logfile

	if [ -z ${CurrentPass+x} ]; then CurrentPass=$NewUserPass; fi

	if [ -z ${Downgrade+x} ]; then
		printf "echo "$CurrentPass" | ./BotDeployLauncher -c config.json -u $NewUser -p $NewUserPass -a ddfun:$ddfunPass -a ddfunadm:$password -b --preserve-data\n"  | tee -a $logfile
		echo "$CurrentPass" | ./BotDeployLauncher -c config.json -u $NewUser -p $NewUserPass -a ddfun:$ddfunPass -a ddfunadm:$password -b --preserve-data
	else
		printf "echo "$CurrentPass" | ./BotDeployLauncher -c config.json -u $NewUser -p $NewUserPass -a ddfun:$ddfunPass -a ddfunadm:$password -b --downgrade --preserve-data\n" | tee -a $logfile
		echo "$CurrentPass" | ./BotDeployLauncher -c config.json -u $NewUser -p $NewUserPass -a ddfun:$ddfunPass -a ddfunadm:$password -b --downgrade --preserve-data
	fi
	printf "\n$(date) Done\n" | tee -a $logfile
}

## Machine checks
function_get-SN-Hostname

## Setup machine for PowerShell & Key Vault
function_generate-password
function_get-PowerShell
function_get-KV


## BotDeploy functions
function_set-workflow
function_get-launcher
function_set-config
function_exec-launcher

exit














